### ISSUE TITLE
Fix Archive search Digest Error

### ISSUE THREAD

**Issue by S3BzA** [COS301-SE-2024/Dispute-Resolution-Engine#248]
When entering search term in archive search, followed by pressing enter...
![image](https://github.com/user-attachments/assets/e9a71d23-4502-453e-a58b-0f57f49c983b)
Outcome...
![image](https://github.com/user-attachments/assets/cb4637f0-a41c-4982-b02c-44b1373d41c1)

**API Log**
```json
{"caller_file":"/app/handlers/archive.go","caller_function":"SearchArchive","caller_line":37,"level":"info","message":"No disputes found","timestamp":"2024-07-23T19:31:35Z"}
```

**FE Log**
```
2024-07-23 21:31:35 Failed to update prerender cache for 6f08f4f0593174f662b6c22329a0130dd432c199c2b8314af5be59be463d8d26 [Error: EACCES: permission denied, mkdir '/usr/src/app/.next/cache/fetch-cache'] {
2024-07-23 21:31:35   errno: -13,
2024-07-23 21:31:35   code: 'EACCES',
2024-07-23 21:31:35   syscall: 'mkdir',
2024-07-23 21:31:35   path: '/usr/src/app/.next/cache/fetch-cache'
2024-07-23 21:31:35 }
2024-07-23 21:31:35 TypeError: Cannot read properties of undefined (reading 'map')
2024-07-23 21:31:35     at C (/usr/src/app/.next/server/app/archive/search/page.js:6:3506) {
2024-07-23 21:31:35   digest: '3849362473'
2024-07-23 21:31:35 }
2024-07-23 21:31:35 TypeError: Cannot read properties of undefined (reading 'map')
2024-07-23 21:31:35     at C (/usr/src/app/.next/server/app/archive/search/page.js:6:3506) {
2024-07-23 21:31:35   digest: '3849362473'
2024-07-23 21:31:35 }
```

**Comment by ghost** [comment]
It seems there was an issue with contract compliance. Tested and working in development environment:


![Image](https://github.com/user-attachments/assets/ff49b7ed-3ce0-4340-8d3e-4d77b5f9e208)
